Repository SOPT-29th-Joint-Seminar-2/LOM-iOS, pull requests merged in 2021-11, with the labels that each got.

#12 Feature/#8 jh book info get
  LOM-iOS/LOM-iOS/Source/Detail/Cell/DetailReviewTVC.swift
  LOM-iOS/LOM-iOS/Source/Detail/Cell/DetailReviewTVC.xib
  LOM-iOS/LOM-iOS/Source/Detail/Detail.storyboard
  LOM-iOS/LOM-iOS/Source/Detail/DetailVC.swift
Labels: Chore, 록시보이

#13 ✨[FEAT] 탭바아이콘 추가
  LOM-iOS/LOM-iOS/Source/Base.lproj/Main.storyboard
  LOM-iOS/LOM-iOS/Source/Home/Home.storyboard
Labels: 씨워터

#14 Feature/#5 hs
  LOM-iOS/LOM-iOS/Source/Seawater/Cell/SeawaterDetailReviewTVC.swift
  LOM-iOS/LOM-iOS/Source/Seawater/Seawater.storyboard
  LOM-iOS/LOM-iOS/Source/Seawater/SeawaterDetailVC.swift
  LOM-iOS/LOM-iOS/Source/Seawater/SeawaterHomeVC.swift
Labels: 씨워터

#19 Feature/#16 jh review get
  LOM-iOS/LOM-iOS/Configuration/Network/APIConstants.swift
  LOM-iOS/LOM-iOS/Configuration/Network/DetailInfoGetService.swift
  LOM-iOS/LOM-iOS/Configuration/Network/DetailResponseData.swift
  LOM-iOS/LOM-iOS/Source/Detail/Cell/DetailReviewTVC.swift
  LOM-iOS/LOM-iOS/Source/Detail/Cell/DetailReviewTVC.xib
  LOM-iOS/LOM-iOS/Source/Detail/DetailVC.swift
  LOM-iOS/LOM-iOS/Source/Home/HomeVC.swift
Labels: Feat, 록시보이
